### ISSUE TITLE
Add example data

### ISSUE THREAD

**Issue by antagomir** [JuliaTurkuDataScience/MicrobiomeAnalysis.jl#21]
Add example data set in the package.

The data could be transferred from the [microbiomeDataSets](https://microbiome.github.io/microbiomeDataSets/reference/index.html). For instance GrieneisenTSData or OKeefeDSData. 

One could either 1) download the data, then store as CSV, load to Julia, prepare data in the correct format and store in the Julia package; or 2) download the data directly from web and process on the fly.

[Artifact](https://pkgdocs.julialang.org/v1/artifacts/) seems to provide useful capacities for example data. Alternatives could be discussed before implementation.

**Comment by antagomir** [comment]
Downloading in R:

```
tse <- microbiomeDataSets::GrieneisenTSData()
coldata <- colData(tse)
rowdata <- rowData(tse)
assaydata <- assay(tse)
```

**Comment by RiboRings** [comment]
Hi! Is there a way to access the HintikkaXO data set directly online? I couldn't find it in the publication

**Comment by antagomir** [comment]
Ok we now seem to have HintikkaXO (MAE) nicely added. 

Shall we add another example data, for instance GrieneisenTSData (SE) is good for demonstration purposes.

Or shalle we close this issue.

**Comment by RiboRings** [comment]
Sure, I can also add an se. GrieneisenTSData is very big. I'm wondering if a smaller experiment would achieve the same goal, and load faster because it's smaller. What's your opinion?

**Comment by antagomir** [comment]
If loading time really is a bottleneck then I agree.

Then we could use OKeefeDSData

**Comment by RiboRings** [comment]
OKeefeDSData is also available now!
