### ISSUE TITLE
Generic instructions

### ISSUE THREAD

**Issue by antagomir** [JuliaTurkuDataScience/MicrobiomeAnalysis.jl#32]
Add generic instructions on the following - at the minimum, just links when these things are well documented elsewhere, NO need to duplicate info; or if the thing is self-explanatory by just looking at the package contents, then no need to add links or instructions, either. Let's keep it simple. 

- How to register a new Julia package
- How to check and build a Julia package after changes to make sure it works
- Where to find good instructions on the coding style and recommended practices in developing Julia packages
- How to add unit tests
- How to document new functions
- How to add new tutorial examples
- How to edit the package website
- How to add example data
- Anything else important?

This information could be either in the "Wiki" area of this repository, or it could be a separate markdown document.

Link to the instruction document from the README, so that it is easy to find.

**Comment by RiboRings** [comment]
Hi! Did you check [PkgTutorial.jl](https://github.com/JuliaTurkuDataScience/PkgTutorial.jl)? If you click on the docs badge in the readme, it'll take you to the guide.

**Comment by antagomir** [comment]
Ah ok. I checked the README text and forgot to check the badge. Looks good!
