### ISSUE TITLE
Importers

### ISSUE THREAD

**Issue by antagomir** [JuliaTurkuDataScience/MicrobiomeAnalysis.jl#39]
The ability to import common microbiome data formats to SE/MAE structures is essential.

The [BiobakeryUtils.jl](http://docs.ecojulia.org/BiobakeryUtils.jl/latest/) already has functions to import Biobakery outputs, in particular humann3 and metaphlan3 data important to Julia and associated object manipulation. This functionality should not be replicated. But the missing piece is to provide a converter that helps to convert the data to SE/MAE after it has been imported by using BiobakeryUtils.jl - more specific task will be to:

Biobakery conversion:
- create conversion function from CommunityProfile to SE and add a reproducible example that shows how this works; we could use either one of the example data sets from the Biobakery tutorial (if license allows + citing the original source); or we can put one of our own data sets (HintikkaXOData) to CommunityProfile format to show how it can be converted back to SE/MAE. Former might be more clear, latter might be confusing (to have many different versions for the Hintikka data)
- show how to combine two SE's to MAE (e.g. metaphlan + humann outputs as the SEs)
- link to the [BiobakeryUtils.jl tutorial](docs.ecojulia.org/BiobakeryUtils.jl/) for further tools for humann3 & metaphlan3 wrangling (we will now focus instead on the downstream tools that can be used more generally also with other measurement/preprocessing tools, not just the Biobakery)

CSV import: 
- add examples on how to import data from simple CSV files to SE 
--> Feel free to open this as a separate issue that can be solved later

 Later:
- biom files
- QIIME2 outputs
- other..
- --> Feel free to open these as a separate issues that can be solved later

**Comment by RiboRings** [comment]
CSV import tasks were completed with [this issue](https://github.com/JuliaTurkuDataScience/MicrobiomeAnalysis.jl/issues/45).

**Comment by RiboRings** [comment]
Biobakery conversion:
- [x] create conversion function from CommunityProfile to SE and add a reproducible example that shows how this works.
This is shown in [the docs](https://juliaturkudatascience.github.io/MicrobiomeAnalysis.jl/dev/example4/).
- [x] show how to combine two SE's to MAE (e.g. metaphlan + humann outputs as the SEs).
This operation is shown in [the docs](https://juliaturkudatascience.github.io/MicrobiomeAnalysis.jl/dev/example2/).
- [x] link to the BiobakeryUtils.jl tutorials.
